// Code generated by the Encore v1.58.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-43gg8.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the 43gg8 Encore application.
 */
export default class Client {
    public readonly edge: edge.ServiceClient
    public readonly integrationhub: integrationhub.ServiceClient
    public readonly mcpgateway: mcpgateway.ServiceClient
    public readonly workerbridge: workerbridge.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.edge = new edge.ServiceClient(base)
        this.integrationhub = new integrationhub.ServiceClient(base)
        this.mcpgateway = new mcpgateway.ServiceClient(base)
        this.workerbridge = new workerbridge.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: edge.AuthParams | AuthDataGenerator
}

export namespace edge {
    export interface AuthParams {
        authorization?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acknowledgeIncident = this.acknowledgeIncident.bind(this)
            this.approveAutomationRun = this.approveAutomationRun.bind(this)
            this.authorize = this.authorize.bind(this)
            this.beginGuestPasskeyRegistration = this.beginGuestPasskeyRegistration.bind(this)
            this.beginOwnerPasskeyRegistration = this.beginOwnerPasskeyRegistration.bind(this)
            this.beginPasskeyAuthentication = this.beginPasskeyAuthentication.bind(this)
            this.cancelAutomationRun = this.cancelAutomationRun.bind(this)
            this.clarifyIntentRun = this.clarifyIntentRun.bind(this)
            this.createEnergyRecommendation = this.createEnergyRecommendation.bind(this)
            this.createIncident = this.createIncident.bind(this)
            this.createRecoveryCodes = this.createRecoveryCodes.bind(this)
            this.escalateIncident = this.escalateIncident.bind(this)
            this.evaluatePolicy = this.evaluatePolicy.bind(this)
            this.finishOwnerPasskeyRegistration = this.finishOwnerPasskeyRegistration.bind(this)
            this.finishPasskeyAuthentication = this.finishPasskeyAuthentication.bind(this)
            this.getAutomationDefinition = this.getAutomationDefinition.bind(this)
            this.getAutomationPlan = this.getAutomationPlan.bind(this)
            this.getAutomationRun = this.getAutomationRun.bind(this)
            this.getAutomationRunAudit = this.getAutomationRunAudit.bind(this)
            this.getHomeTopology = this.getHomeTopology.bind(this)
            this.getIntentRun = this.getIntentRun.bind(this)
            this.getSleepContext = this.getSleepContext.bind(this)
            this.homeAssistantStatus = this.homeAssistantStatus.bind(this)
            this.identityManifest = this.identityManifest.bind(this)
            this.incidentAudit = this.incidentAudit.bind(this)
            this.incidentWorkflowState = this.incidentWorkflowState.bind(this)
            this.ingestEnergyReading = this.ingestEnergyReading.bind(this)
            this.interpretIntent = this.interpretIntent.bind(this)
            this.listHomeEntities = this.listHomeEntities.bind(this)
            this.listIncidents = this.listIncidents.bind(this)
            this.modelGatewayStatus = this.modelGatewayStatus.bind(this)
            this.previewIntent = this.previewIntent.bind(this)
            this.previewSleepPlan = this.previewSleepPlan.bind(this)
            this.publishAutomation = this.publishAutomation.bind(this)
            this.publishAutomationPlan = this.publishAutomationPlan.bind(this)
            this.publishLeakPlaybook = this.publishLeakPlaybook.bind(this)
            this.putEnergyTariff = this.putEnergyTariff.bind(this)
            this.recoverOwner = this.recoverOwner.bind(this)
            this.resolveIncident = this.resolveIncident.bind(this)
            this.saveAutomationDraft = this.saveAutomationDraft.bind(this)
            this.saveLeakPlaybookDraft = this.saveLeakPlaybookDraft.bind(this)
            this.simulateAutomation = this.simulateAutomation.bind(this)
            this.startAutomationPlan = this.startAutomationPlan.bind(this)
            this.startHomeAssistantStream = this.startHomeAssistantStream.bind(this)
            this.startIntentRun = this.startIntentRun.bind(this)
            this.stopHomeAssistantStream = this.stopHomeAssistantStream.bind(this)
            this.syncHomeAssistant = this.syncHomeAssistant.bind(this)
            this.temporalStatus = this.temporalStatus.bind(this)
        }

        public async acknowledgeIncident(incidentId: string): Promise<shared.IncidentView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/incidents/${encodeURIComponent(incidentId)}/acknowledge`)
            return await resp.json() as shared.IncidentView
        }

        public async approveAutomationRun(workflowId: string, params: shared.ApprovalDecisionView): Promise<{
    workflowId: string
    accepted: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/runs/${encodeURIComponent(workflowId)}/approval`, JSON.stringify(params))
            return await resp.json() as {
    workflowId: string
    accepted: true
}
        }

        public async authorize(params: shared.AuthorizationRequestView): Promise<shared.AuthorizationDecisionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/authorize`, JSON.stringify(params))
            return await resp.json() as shared.AuthorizationDecisionView
        }

        public async beginGuestPasskeyRegistration(params: {
    sessionToken: string
    displayName: string
    homeId: string
    areaId?: string
    capability?: string
    riskCeiling: "R0" | "R1" | "R2" | "R3" | "R4"
    expiresAt: string
}): Promise<{
    principalId: string
    challengeId: string
    optionsJson: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/passkeys/guests/registration/options`, JSON.stringify(params))
            return await resp.json() as {
    principalId: string
    challengeId: string
    optionsJson: string
}
        }

        public async beginOwnerPasskeyRegistration(params: {
    displayName: string
    bootstrapCode: string
}): Promise<{
    principalId: string
    challengeId: string
    optionsJson: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/passkeys/owner/registration/options`, JSON.stringify(params))
            return await resp.json() as {
    principalId: string
    challengeId: string
    optionsJson: string
}
        }

        public async beginPasskeyAuthentication(params: {
    principalId?: string
}): Promise<{
    challengeId: string
    optionsJson: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/passkeys/authentication/options`, JSON.stringify(params))
            return await resp.json() as {
    challengeId: string
    optionsJson: string
}
        }

        public async cancelAutomationRun(workflowId: string): Promise<{
    workflowId: string
    accepted: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/runs/${encodeURIComponent(workflowId)}/cancel`)
            return await resp.json() as {
    workflowId: string
    accepted: true
}
        }

        public async clarifyIntentRun(workflowId: string, params: shared.AgentClarificationView): Promise<{
    accepted: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/intents/runs/${encodeURIComponent(workflowId)}/clarification`, JSON.stringify(params))
            return await resp.json() as {
    accepted: true
}
        }

        public async createEnergyRecommendation(homeId: string, params: {
    flexibleEnergyKWh: number
    at: string
}): Promise<shared.EnergyRecommendationView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/energy/homes/${encodeURIComponent(homeId)}/recommendations`, JSON.stringify(params))
            return await resp.json() as shared.EnergyRecommendationView
        }

        public async createIncident(params: {
    homeId: string
    dedupeKey: string
    severity: "info" | "warning" | "critical"
    title: string
    body: string
}): Promise<{
    incident: shared.IncidentView
    deduplicated: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/incidents`, JSON.stringify(params))
            return await resp.json() as {
    incident: shared.IncidentView
    deduplicated: boolean
}
        }

        public async createRecoveryCodes(params: {
    sessionToken: string
}): Promise<{
    recoveryCodes: string[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/recovery/codes`, JSON.stringify(params))
            return await resp.json() as {
    recoveryCodes: string[]
}
        }

        public async escalateIncident(incidentId: string): Promise<shared.IncidentView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/incidents/${encodeURIComponent(incidentId)}/escalate`)
            return await resp.json() as shared.IncidentView
        }

        public async evaluatePolicy(params: shared.EvaluatePolicyRequest): Promise<shared.PolicyDecisionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/policy/evaluate`, JSON.stringify(params))
            return await resp.json() as shared.PolicyDecisionView
        }

        public async finishOwnerPasskeyRegistration(params: {
    principalId: string
    challengeId: string
    responseJson: string
}): Promise<shared.SessionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/passkeys/owner/registration/verify`, JSON.stringify(params))
            return await resp.json() as shared.SessionView
        }

        public async finishPasskeyAuthentication(params: {
    challengeId: string
    responseJson: string
}): Promise<shared.SessionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/passkeys/authentication/verify`, JSON.stringify(params))
            return await resp.json() as shared.SessionView
        }

        public async getAutomationDefinition(automationId: string, version: number): Promise<shared.AutomationDefinitionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/automations/${encodeURIComponent(automationId)}/versions/${encodeURIComponent(version)}`)
            return await resp.json() as shared.AutomationDefinitionView
        }

        public async getAutomationPlan(planId: string, version: number): Promise<shared.ActionPlanView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/plans/${encodeURIComponent(planId)}/versions/${encodeURIComponent(version)}`)
            return await resp.json() as shared.ActionPlanView
        }

        public async getAutomationRun(workflowId: string): Promise<shared.AutomationRunView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/runs/${encodeURIComponent(workflowId)}`)
            return await resp.json() as shared.AutomationRunView
        }

        public async getAutomationRunAudit(workflowId: string): Promise<{
    workflowId: string
    events: shared.AutomationAuditEventView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/runs/${encodeURIComponent(workflowId)}/audit`)
            return await resp.json() as {
    workflowId: string
    events: shared.AutomationAuditEventView[]
}
        }

        public async getHomeTopology(homeId: string): Promise<shared.TopologyView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/homes/${encodeURIComponent(homeId)}/topology`)
            return await resp.json() as shared.TopologyView
        }

        public async getIntentRun(workflowId: string): Promise<shared.AgentIntentStateView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/intents/runs/${encodeURIComponent(workflowId)}`)
            return await resp.json() as shared.AgentIntentStateView
        }

        public async getSleepContext(homeId: string): Promise<shared.SleepContextView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/homes/${encodeURIComponent(homeId)}/sleep-context`)
            return await resp.json() as shared.SleepContextView
        }

        public async homeAssistantStatus(): Promise<shared.IntegrationCheckpointView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/integrations/home-assistant/status`)
            return await resp.json() as shared.IntegrationCheckpointView
        }

        public async identityManifest(): Promise<shared.IdentityManifestView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/identity/manifest`)
            return await resp.json() as shared.IdentityManifestView
        }

        public async incidentAudit(incidentId: string): Promise<{
    incidentId: string
    events: shared.IncidentAuditView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/incidents/${encodeURIComponent(incidentId)}/audit`)
            return await resp.json() as {
    incidentId: string
    events: shared.IncidentAuditView[]
}
        }

        public async incidentWorkflowState(workflowId: string): Promise<{
    stateJson: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/incidents/${encodeURIComponent(workflowId)}/workflow`)
            return await resp.json() as {
    stateJson: string
}
        }

        public async ingestEnergyReading(params: {
    homeId: string
    meterId: string
    observedAt: string
    powerW: number
    energyKWh: number
}): Promise<shared.EnergyReadingView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/energy/readings`, JSON.stringify(params))
            return await resp.json() as shared.EnergyReadingView
        }

        public async interpretIntent(params: shared.ResidentIntentRequestView): Promise<shared.IntentInterpretationView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/intents/interpret`, JSON.stringify(params))
            return await resp.json() as shared.IntentInterpretationView
        }

        public async listHomeEntities(homeId: string): Promise<{
    homeId: string
    entities: shared.EntityView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/homes/${encodeURIComponent(homeId)}/entities`)
            return await resp.json() as {
    homeId: string
    entities: shared.EntityView[]
}
        }

        public async listIncidents(homeId: string): Promise<{
    homeId: string
    incidents: shared.IncidentView[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/homes/${encodeURIComponent(homeId)}/incidents`)
            return await resp.json() as {
    homeId: string
    incidents: shared.IncidentView[]
}
        }

        public async modelGatewayStatus(): Promise<{
    provider: "openrouter"
    profile: "intent-fast"
    isolated: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/models/status`)
            return await resp.json() as {
    provider: "openrouter"
    profile: "intent-fast"
    isolated: true
}
        }

        public async previewIntent(params: shared.ResidentIntentRequestView): Promise<shared.IntentPlanPreviewView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/intents/preview`, JSON.stringify(params))
            return await resp.json() as shared.IntentPlanPreviewView
        }

        public async previewSleepPlan(homeId: string, params: shared.SleepPlanPreviewRequestView): Promise<shared.SleepPlanPreviewView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/homes/${encodeURIComponent(homeId)}/plans/sleep/preview`, JSON.stringify(params))
            return await resp.json() as shared.SleepPlanPreviewView
        }

        public async publishAutomation(automationId: string, version: number): Promise<shared.AutomationDefinitionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/automations/${encodeURIComponent(automationId)}/versions/${encodeURIComponent(version)}/publish`)
            return await resp.json() as shared.AutomationDefinitionView
        }

        public async publishAutomationPlan(params: shared.ActionPlanView): Promise<shared.ActionPlanView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/plans`, JSON.stringify(params))
            return await resp.json() as shared.ActionPlanView
        }

        public async publishLeakPlaybook(playbookId: string, version: number): Promise<shared.LeakPlaybookView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/incident-playbooks/${encodeURIComponent(playbookId)}/versions/${encodeURIComponent(version)}/publish`)
            return await resp.json() as shared.LeakPlaybookView
        }

        public async putEnergyTariff(params: {
    homeId: string
    startsAt: string
    endsAt: string
    pricePerKWh: number
    currency: string
}): Promise<shared.EnergyTariffView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/energy/tariffs`, JSON.stringify(params))
            return await resp.json() as shared.EnergyTariffView
        }

        public async recoverOwner(params: {
    principalId: string
    recoveryCode: string
}): Promise<shared.SessionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/identity/recovery/verify`, JSON.stringify(params))
            return await resp.json() as shared.SessionView
        }

        public async resolveIncident(incidentId: string, params: {
    status: "resolved" | "false_positive"
    note: string
}): Promise<{
    accepted: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/incidents/${encodeURIComponent(incidentId)}/resolve`, JSON.stringify(params))
            return await resp.json() as {
    accepted: true
}
        }

        public async saveAutomationDraft(params: shared.AutomationDefinitionView): Promise<shared.AutomationDefinitionView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/automations/drafts`, JSON.stringify(params))
            return await resp.json() as shared.AutomationDefinitionView
        }

        public async saveLeakPlaybookDraft(homeId: string, params: {
    playbookId?: string
    name: string
    mode: "active" | "test"
    acknowledgementTimeoutMs: number
    actions: shared.IncidentPlaybookActionView[]
}): Promise<shared.LeakPlaybookView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/homes/${encodeURIComponent(homeId)}/incident-playbooks/leak/drafts`, JSON.stringify(params))
            return await resp.json() as shared.LeakPlaybookView
        }

        public async simulateAutomation(automationId: string, version: number, params: {
    snapshotJson: string
    replayedAt: string
}): Promise<shared.AutomationSimulationView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/automations/${encodeURIComponent(automationId)}/versions/${encodeURIComponent(version)}/simulate`, JSON.stringify(params))
            return await resp.json() as shared.AutomationSimulationView
        }

        public async startAutomationPlan(planId: string, version: number, params: {
    requestedBy?: string
}): Promise<{
    workflowId: string
    runId: string
    planId: string
    version: number
    startedAt: string
    status: "running"
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/plans/${encodeURIComponent(planId)}/versions/${encodeURIComponent(version)}/runs`, JSON.stringify(params))
            return await resp.json() as {
    workflowId: string
    runId: string
    planId: string
    version: number
    startedAt: string
    status: "running"
}
        }

        public async startHomeAssistantStream(): Promise<{
    streaming: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/integrations/home-assistant/stream/start`)
            return await resp.json() as {
    streaming: true
}
        }

        public async startIntentRun(params: shared.ResidentIntentRequestView): Promise<{
    workflowId: string
    runId: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/intents/runs`, JSON.stringify(params))
            return await resp.json() as {
    workflowId: string
    runId: string
}
        }

        public async stopHomeAssistantStream(): Promise<{
    streaming: false
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/integrations/home-assistant/stream/stop`)
            return await resp.json() as {
    streaming: false
}
        }

        public async syncHomeAssistant(): Promise<shared.HomeAssistantSyncView> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/v1/integrations/home-assistant/sync`)
            return await resp.json() as shared.HomeAssistantSyncView
        }

        public async temporalStatus(): Promise<{
    engine: "temporal"
    ownership: "external"
    taskQueue: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/v1/temporal/status`)
            return await resp.json() as {
    engine: "temporal"
    ownership: "external"
    taskQueue: string
}
        }
    }
}

export namespace integrationhub {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ingestSignedEntityState = this.ingestSignedEntityState.bind(this)
        }

        public async ingestSignedEntityState(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/integrations/webhooks/entity-state`, body, options)
        }
    }
}

export namespace mcpgateway {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.mcp = this.mcp.bind(this)
        }

        public async mcp(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/mcp`, body, options)
        }
    }
}

export namespace workerbridge {
    export interface Authorized {
        authorization?: string
    }

    export interface Authorized {
        eventType: string
        actor: string
        detailsJson: string
        authorization?: string
    }

    export interface Authorized {
        workflowId: string
        evidenceJson: string
        playbookJson: string
        authorization?: string
    }

    export interface Authorized {
        utterance: string
        requestedBy?: string
        homeId?: string
        authorization?: string
    }

    export interface Authorized {
        homeId: string
        requestedBy?: string
        climateTargetC?: number
        closeCovers?: boolean
        armAlarm?: boolean
        dryRun?: boolean
        authorization?: string
    }

    export interface Authorized {
        severity: "info" | "warning" | "critical"
        channel: string
        recipient: string
        status: "delivered" | "skipped"
        dedupeKey: string
        ttlSeconds: number
        requiredAck: boolean
        escalationStep: number
        failureMessage?: string
        authorization?: string
    }

    export interface Authorized {
        status: "open" | "acknowledged" | "mitigated" | "monitoring" | "resolved" | "false_positive"
        eventType: string
        actor: string
        detailsJson: string
        escalationStep?: number
        principalId?: string
        note?: string
        authorization?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.activeLeakPlaybook = this.activeLeakPlaybook.bind(this)
            this.appendIncidentEvent = this.appendIncidentEvent.bind(this)
            this.createIncidentRecord = this.createIncidentRecord.bind(this)
            this.interpretIntent = this.interpretIntent.bind(this)
            this.previewSleep = this.previewSleep.bind(this)
            this.recordIncidentDelivery = this.recordIncidentDelivery.bind(this)
            this.transitionIncident = this.transitionIncident.bind(this)
        }

        public async activeLeakPlaybook(homeId: string, params: Authorized<{
    homeId: string
}>): Promise<{
    playbookJson: string
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/workers/v1/homes/${encodeURIComponent(homeId)}/incident-playbooks/leak/active`, undefined, {headers})
            return await resp.json() as {
    playbookJson: string
}
        }

        public async appendIncidentEvent(incidentId: string, params: Authorized<{
    incidentId: string
    eventType: string
    actor: string
    detailsJson: string
}>): Promise<{
    accepted: true
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                actor:       params.actor,
                detailsJson: params.detailsJson,
                eventType:   params.eventType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/incidents/${encodeURIComponent(incidentId)}/events`, JSON.stringify(body), {headers})
            return await resp.json() as {
    accepted: true
}
        }

        public async createIncidentRecord(params: Authorized<{
    workflowId: string
    evidenceJson: string
    playbookJson: string
}>): Promise<{
    incidentId: string
    deduplicated: boolean
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                evidenceJson: params.evidenceJson,
                playbookJson: params.playbookJson,
                workflowId:   params.workflowId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/incidents`, JSON.stringify(body), {headers})
            return await resp.json() as {
    incidentId: string
    deduplicated: boolean
}
        }

        public async interpretIntent(params: Authorized<shared.ResidentIntentRequestView>): Promise<shared.IntentInterpretationView> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                homeId:      params.homeId,
                requestedBy: params.requestedBy,
                utterance:   params.utterance,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/intents/interpret`, JSON.stringify(body), {headers})
            return await resp.json() as shared.IntentInterpretationView
        }

        public async previewSleep(params: Authorized<shared.SleepPlanPreviewRequestView>): Promise<shared.SleepPlanPreviewView> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                armAlarm:       params.armAlarm,
                climateTargetC: params.climateTargetC,
                closeCovers:    params.closeCovers,
                dryRun:         params.dryRun,
                homeId:         params.homeId,
                requestedBy:    params.requestedBy,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/plans/sleep/preview`, JSON.stringify(body), {headers})
            return await resp.json() as shared.SleepPlanPreviewView
        }

        public async recordIncidentDelivery(incidentId: string, params: Authorized<{
    incidentId: string
    severity: "info" | "warning" | "critical"
    channel: string
    recipient: string
    status: "delivered" | "skipped"
    dedupeKey: string
    ttlSeconds: number
    requiredAck: boolean
    escalationStep: number
    failureMessage?: string
}>): Promise<{
    accepted: true
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                channel:        params.channel,
                dedupeKey:      params.dedupeKey,
                escalationStep: params.escalationStep,
                failureMessage: params.failureMessage,
                recipient:      params.recipient,
                requiredAck:    params.requiredAck,
                severity:       params.severity,
                status:         params.status,
                ttlSeconds:     params.ttlSeconds,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/incidents/${encodeURIComponent(incidentId)}/deliveries`, JSON.stringify(body), {headers})
            return await resp.json() as {
    accepted: true
}
        }

        public async transitionIncident(incidentId: string, params: Authorized<{
    incidentId: string
    status: "open" | "acknowledged" | "mitigated" | "monitoring" | "resolved" | "false_positive"
    eventType: string
    actor: string
    detailsJson: string
    escalationStep?: number
    principalId?: string
    note?: string
}>): Promise<{
    accepted: true
}> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                actor:          params.actor,
                detailsJson:    params.detailsJson,
                escalationStep: params.escalationStep,
                eventType:      params.eventType,
                note:           params.note,
                principalId:    params.principalId,
                status:         params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/workers/v1/incidents/${encodeURIComponent(incidentId)}/transition`, JSON.stringify(body), {headers})
            return await resp.json() as {
    accepted: true
}
        }
    }
}

export namespace shared {
    export interface ActionExecutionView {
        actionId: string
        commandId: string
        status: "pending" | "approved" | "executing" | "confirmed" | "rejected" | "failed" | "compensated" | "skipped"
        policy?: PolicyDecisionView
        startedAt?: string
        finishedAt?: string
        observedValue?: JsonScalarView
        error?: string
    }

    export interface ActionPlanView {
        planId: string
        version: number
        homeId: string
        title: string
        requestedBy: string
        createdAt: string
        actions: ProposedActionView[]
        dryRun: boolean
    }

    export interface ActionPlanView {
        planId: string
        version: number
        homeId: string
        title: string
        requestedBy: string
        createdAt: string
        actions: ProposedActionView[]
        dryRun: boolean
    }

    export interface AgentClarificationView {
        text: string
        providedBy: string
    }

    export interface AgentIntentStateView {
        status: "interpreting" | "awaiting_clarification" | "planning" | "completed" | "failed"
        request: {
            utterance: string
            requestedBy: string
        }
        attempt: number
        interpretation?: IntentInterpretationView
        preview?: SleepPlanPreviewView
        error?: string
    }

    export interface ApprovalDecisionView {
        approvalId: string
        approved: boolean
        decidedBy: string
        decidedAt: string
    }

    export interface AreaView {
        id: string
        homeId: string
        name: string
        kind: "room" | "zone" | "floor" | "exterior" | "logical"
        externalRef: {
            system: "home_assistant" | "mqtt" | "webhook" | "virtual"
            instanceId: string
            areaId: string
        }
    }

    export interface AuthorizationDecisionView {
        allowed: boolean
        principalId?: string
        role?: IdentityRoleView
        reason: string
    }

    export interface AuthorizationRequestView {
        sessionToken: string
        homeId: string
        areaId?: string
        deviceId?: string
        capability?: string
        risk?: RiskClassView
    }

    export interface AutomationActionView {
        capability: string
        entityId: string
        input: { [key: string]: JsonScalarView }
        risk: RiskClassView
    }

    export interface AutomationAuditEventView {
        sequence: number
        eventId: string
        workflowId: string
        runId: string
        planId: string
        eventType: string
        occurredAt: string
        actor: string
        details: { [key: string]: JsonScalarView }
    }

    export interface AutomationDefinitionView {
        automationId: string
        version: number
        homeId: string
        name: string
        status: "draft" | "published" | "retired"
        mode: "shadow" | "active"
        trigger: {
            kind: "state" | "schedule" | "energy"
            entityId?: string
            expression: string
        }
        conditions: {
            entityId: string
            operator: "eq" | "neq" | "gt" | "gte" | "lt" | "lte"
            value: JsonScalarView
        }[]
        actions: AutomationActionView[]
        budgets: {
            maxActionsPerRun: number
            maxRunsPerHour: number
            maxRisk: RiskClassView
        }
        locks: string[]
        rollback: "required" | "best_effort" | "none"
        shadowEvidenceId?: string
        policyPromotionId?: string
        createdAt: string
    }

    export interface AutomationDefinitionView {
        automationId: string
        version: number
        homeId: string
        name: string
        status: "draft" | "published" | "retired"
        mode: "shadow" | "active"
        trigger: {
            kind: "state" | "schedule" | "energy"
            entityId?: string
            expression: string
        }
        conditions: {
            entityId: string
            operator: "eq" | "neq" | "gt" | "gte" | "lt" | "lte"
            value: JsonScalarView
        }[]
        actions: AutomationActionView[]
        budgets: {
            maxActionsPerRun: number
            maxRunsPerHour: number
            maxRisk: RiskClassView
        }
        locks: string[]
        rollback: "required" | "best_effort" | "none"
        shadowEvidenceId?: string
        policyPromotionId?: string
        createdAt: string
    }

    export interface AutomationRunStateView {
        planId: string
        status: string
        currentAction: number
        actions: ActionExecutionView[]
        pendingApprovalId?: string
        approval?: {
            approvalId: string
            approved: boolean
            decidedBy: string
            decidedAt: string
        }
        startedAt: string
        finishedAt?: string
        error?: string
    }

    export interface AutomationRunView {
        workflowId: string
        runId: string
        planId: string
        version: number
        startedAt: string
        status: string
        finishedAt?: string
        state: AutomationRunStateView
    }

    export interface AutomationSimulationView {
        automationId: string
        version: number
        triggered: boolean
        conditionsPassed: boolean
        proposedActions: AutomationActionView[]
        blockedReasons: string[]
        effectful: false
        replayedAt: string
    }

    export interface CommandView {
        commandId: string
        idempotencyKey: string
        capability: string
        target: {
            homeId: string
            entityId?: string
            areaId?: string
            selector?: string
        }
        input: { [key: string]: JsonScalarView }
        risk: RiskClassView
        dryRun: boolean
    }

    export interface DeviceView {
        id: string
        homeId: string
        areaId?: string
        name: string
        manufacturer?: string
        model?: string
        integration: string
        externalRef: {
            system: "home_assistant" | "mqtt" | "webhook" | "virtual"
            instanceId: string
            deviceId: string
        }
    }

    export interface EnergyReadingView {
        readingId: string
        homeId: string
        meterId: string
        observedAt: string
        powerW: number
        energyKWh: number
    }

    export interface EnergyRecommendationView {
        recommendationId: string
        homeId: string
        generatedAt: string
        title: string
        rationale: string
        suggestedStartAt: string
        estimatedSavings: number
        currency: string
        effectful: false
    }

    export interface EnergyTariffView {
        tariffId: string
        homeId: string
        startsAt: string
        endsAt: string
        pricePerKWh: number
        currency: string
    }

    export interface EntityView {
        id: string
        homeId: string
        deviceId?: string
        areaId?: string
        name: string
        domain: string
        deviceClass?: string
        capabilities: string[]
        externalRef: {
            system: "home_assistant" | "mqtt" | "webhook" | "virtual"
            instanceId: string
            entityId: string
        }
        observedState: ObservedStateView
    }

    export interface EvaluatePolicyRequest {
        capability: string
        declaredRisk?: RiskClassView
        preauthorizedPlaybook?: boolean
        dryRun?: boolean
    }

    export interface ExpectedObservationView {
        entityId: string
        attribute: string
        equals: JsonScalarView
        timeoutMs: number
    }

    export interface HomeAssistantSyncView {
        homeId: string
        source: "home_assistant"
        discovered: number
        published: number
        areas: number
        devices: number
        topology: "available" | "degraded"
        syncedAt: string
    }

    export interface IdentityManifestView {
        bootstrap: "local-owner"
        authentication: ("passkey" | "local-recovery")[]
        roles: IdentityRoleView[]
        scopeDimensions: ("home" | "area" | "device" | "capability" | "time" | "risk")[]
        serviceTokens: {
            expiring: true
            leastPrivilege: true
        }
    }

    export type IdentityRoleView = "Owner" | "Admin" | "Member" | "Guest" | "Service Account"

    export interface IncidentAuditView {
        sequence: number
        incidentId: string
        eventType: string
        actor: string
        occurredAt: string
        details: { [key: string]: JsonScalarView }
    }

    export interface IncidentPlaybookActionView {
        actionId: string
        command: CommandView
        expectedObservation: ExpectedObservationView
        compensation?: {
            command: CommandView
            expectedObservation: ExpectedObservationView
        }
    }

    export interface IncidentView {
        incidentId: string
        homeId: string
        dedupeKey: string
        severity: "info" | "warning" | "critical"
        status: "open" | "acknowledged" | "mitigated" | "monitoring" | "resolved" | "false_positive"
        title: string
        body: string
        createdAt: string
        workflowId?: string
        playbookId?: string
        playbookVersion?: number
        sourceEventId?: string
        requiredAck: boolean
        escalationStep: number
        ttlExpiresAt?: string
        acknowledgedAt?: string
        acknowledgedBy?: string
        escalatedAt?: string
        resolvedAt?: string
        resolvedBy?: string
        resolutionNote?: string
    }

    export interface IntegrationCheckpointView {
        homeId: string
        system: "home_assistant"
        instanceId: string
        status: "ok" | "degraded" | "down"
        rest: boolean
        streaming: boolean
        topology: boolean
        lastSyncStartedAt?: string
        lastSyncCompletedAt?: string
        lastSuccessfulSyncAt?: string
        lastFailureAt?: string
        failureMessage?: string
        discoveredEntities: number
        discoveredAreas: number
        discoveredDevices: number
    }

    export interface IntentInterpretationView {
        kind: "sleep" | "unsupported"
        confidence: number
        summary: string
        sleep?: {
            climateTargetC: number
            closeCovers: boolean
            armAlarm: boolean
        }
    }

    export interface IntentPlanPreviewView {
        interpretation: IntentInterpretationView
        preview?: SleepPlanPreviewView
        modelProfile: string
    }

    export type JsonScalarView = string | number | boolean | null

    export interface LeakPlaybookView {
        playbookId: string
        version: number
        homeId: string
        name: string
        status: "draft" | "published" | "retired"
        triggerDeviceClass: "moisture"
        preauthorized: true
        mode: "active" | "test"
        acknowledgementTimeoutMs: number
        actions: IncidentPlaybookActionView[]
        createdAt: string
        publishedAt?: string
    }

    export interface ObservedStateView {
        value: string
        unit?: string
        timestamp: string
        source: string
        quality: StateQuality
        staleAfterSec?: number
    }

    export interface PolicyDecisionView {
        effect: "allow" | "deny" | "require_approval"
        risk: RiskClassView
        reasons: string[]
        approvalId?: string
    }

    export interface ProposedActionView {
        actionId: string
        command: CommandView
        expectedObservation: ExpectedObservationView
        compensation?: {
            command: CommandView
            expectedObservation: ExpectedObservationView
        }
    }

    export interface ResidentIntentRequestView {
        utterance: string
        requestedBy?: string
        homeId?: string
    }

    export interface ResidentIntentRequestView {
        utterance: string
        requestedBy?: string
        homeId?: string
    }

    export interface ResidentIntentRequestView {
        utterance: string
        requestedBy?: string
        homeId?: string
    }

    export interface ResidentIntentRequestView {
        utterance: string
        requestedBy?: string
        homeId?: string
    }

    export type RiskClassView = "R0" | "R1" | "R2" | "R3" | "R4"

    export interface SessionView {
        sessionToken: string
        principalId: string
        role: IdentityRoleView
        expiresAt: string
    }

    export interface SleepContextItemView {
        entityId: string
        name: string
        areaId?: string
        domain: string
        observedState: ObservedStateView
        attention: "ready" | "stale" | "unavailable"
    }

    export interface SleepContextView {
        homeId: string
        generatedAt: string
        readiness: "ready" | "degraded"
        summary: {
            relevant: number
            stale: number
            unavailable: number
        }
        categories: {
            lights: SleepContextItemView[]
            climate: SleepContextItemView[]
            covers: SleepContextItemView[]
            media: SleepContextItemView[]
            alarm: SleepContextItemView[]
        }
    }

    export interface SleepPlanPreviewRequestView {
        requestedBy?: string
        climateTargetC?: number
        closeCovers?: boolean
        armAlarm?: boolean
        dryRun?: boolean
    }

    export interface SleepPlanPreviewRequestView {
        homeId: string
        requestedBy?: string
        climateTargetC?: number
        closeCovers?: boolean
        armAlarm?: boolean
        dryRun?: boolean
    }

    export interface SleepPlanPreviewView {
        plan: ActionPlanView
        skipped: {
            entityId: string
            name: string
            reason: string
        }[]
    }

    export type StateQuality = "good" | "uncertain" | "stale" | "unavailable"

    export interface TopologyView {
        homeId: string
        areas: AreaView[]
        devices: DeviceView[]
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | edge.AuthParams
  | Promise<edge.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "43gg8-Generated-TS-Client (Encore/v1.58.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: edge.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
